### ISSUE TITLE
mac下sublime text2报错

### ISSUE THREAD

**Issue by 5up3rc** [yangweijie/SublimeThinkPHP#6]
Error trying to parse file: Trailing comma before closing bracket in ~/Library/Application Support/Sublime Text 2/Packages/Thinkphp/Default (OSX).sublime-mousemap:3:1

**Comment by yangweijie** [comment]
已修复，昨天提交时发现错了，修改后忘了提交。因为手册查找功能单独写了个PhpNinJaManual插件
